#!/usr/bin/env bash
# =============================================================================
#  04_run_pipeline.sh - generate nextflow.config from project.conf, then run
# =============================================================================
#  The config is GENERATED, never hand-edited. Change hardware by re-running
#  00_configure.sh; this script rewrites the resource ladder to match.
# =============================================================================
STEP=pipeline
source "$(dirname "${BASH_SOURCE[0]:-$0}")/lib_common.sh"
mkdirs

# -----------------------------------------------------------------------------
# 0. Detach from the terminal.
#    Nextflow receives SIGHUP the moment the terminal that launched it goes
#    away - on WSL that is every VS Code "Attempting to reconnect" - and the
#    whole run aborts (every task reports exit 129). Re-launch this script
#    inside a tmux session so it survives: detach with Ctrl-b d, come back with
#    `tmux attach -t riboseq`. Output is still tee'd to LOG_DIR as before.
#    Set NO_TMUX=1 to run in the foreground instead.
# -----------------------------------------------------------------------------
if [[ -t 0 && -z "${TMUX:-}" && -z "${NO_TMUX:-}" ]] && command -v tmux >/dev/null 2>&1; then
    if tmux has-session -t riboseq 2>/dev/null; then
        die "a 'riboseq' tmux session is already running - attach with: tmux attach -t riboseq"
    fi
    SELF="$(readlink -f "${BASH_SOURCE[0]:-$0}")"
    STATUS_FILE="${LOG_DIR}/.pipeline_exit_status"
    rm -f "$STATUS_FILE"
    log "running inside tmux session 'riboseq' (detach: Ctrl-b d, reattach: tmux attach -t riboseq)"
    tmux new-session -s riboseq bash -c \
        "NO_TMUX=1 bash $(printf '%q' "$SELF") $(printf '%q ' "$@"); echo \$? > $(printf '%q' "$STATUS_FILE")"
    if [[ -f "$STATUS_FILE" ]]; then
        exit "$(cat "$STATUS_FILE")"
    fi
    log "detached - the pipeline is still running in tmux session 'riboseq'."
    log "  watch it:  tmux attach -t riboseq      log: ${LOG_DIR}/nextflow_*.log"
    log "  when it finishes, continue with:  bash scripts/run_all.sh --from te"
    exit 1
fi

export_caches
activate_env "$CONDA_ENV_NAME"
cd "$PROJECT_DIR"

SAMPLESHEET="${PROJECT_DIR}/samplesheet.csv"
[[ -f "$SAMPLESHEET" ]] || die "samplesheet.csv not found in ${PROJECT_DIR}"
[[ -s genome.exons.gtf ]] || die "genome.exons.gtf missing - run 02_prepare_genome.sh"
SA_N="${SA_INDEX_NBASES:-14}"

# -----------------------------------------------------------------------------
# 1. Generate nextflow.config
# -----------------------------------------------------------------------------
cat > "${PROJECT_DIR}/nextflow.config" <<EOF
/*
 * GENERATED by 04_run_pipeline.sh from project.conf - do not edit by hand.
 * Machine profile: ${THREADS} threads / ${RAM_GB} GB RAM
 *   ${MAX_MEM_GB} GB usable by tasks, ${RESERVE_GB} GB reserved for OS+JVM+Singularity
 */

workDir = '${WORK_DIR}'

singularity {
    enabled    = true
    autoMounts = true
    cacheDir   = '${CACHE_DIR}/singularity'
    runOptions = '-B ${PROJECT_DIR}'
}

// Ceiling: no single task may exceed the machine.
process {
    resourceLimits = [ cpus: ${THREADS}, memory: ${MAX_MEM_GB}.GB, time: 240.h ]
}

// Total resources shared by all CONCURRENT tasks - stops oversubscription.
executor {
    name            = 'local'
    cpus            = ${THREADS}
    memory          = '${MAX_MEM_GB} GB'
    queueSize       = ${THREADS}
    pollInterval    = '5 sec'
    submitRateLimit = '10/1sec'
}

process {
    errorStrategy = { task.exitStatus in ((130..145) + 104 + 175) ? 'retry' : 'finish' }
    maxRetries    = 2

    // Requests sit below the ceiling on purpose: if process_high took every
    // core, tasks would run one at a time and the box would idle whenever that
    // task was single-threaded. '* task.attempt' keeps retries escalating, and
    // resourceLimits above clamps them.
    withLabel:process_single      { cpus = { 1 };                          memory = { ${LOW_MEM_GB}.GB  * task.attempt }; time = { 4.h  * task.attempt } }
    withLabel:process_low         { cpus = { ${LOW_CPUS}  * task.attempt }; memory = { ${LOW_MEM_GB}.GB  * task.attempt }; time = { 4.h  * task.attempt } }
    withLabel:process_medium      { cpus = { ${MED_CPUS}  * task.attempt }; memory = { ${MED_MEM_GB}.GB  * task.attempt }; time = { 8.h  * task.attempt } }
    withLabel:process_high        { cpus = { ${HIGH_CPUS} * task.attempt }; memory = { ${HIGH_MEM_GB}.GB * task.attempt }; time = { 16.h * task.attempt } }
    withLabel:process_high_memory { memory = { ${HIGHMEM_GB}.GB * task.attempt } }

    // STAR's default suffix-array size suits a mammalian genome; on a small
    // genome it over-allocates and the index is unusable. Computed in
    // 02_prepare_genome.sh from the actual sequence length.
    withName: '.*STAR_GENOMEGENERATE.*' { ext.args = '--genomeSAindexNbases ${SA_N}' }

    // The nf-core samtools/sort module passes no memory flag, so samtools falls
    // back to its own default of 768 MB PER THREAD. As process_medium that is
    // ${MED_CPUS} x 0.75 GB ~ $(( MED_CPUS * 3 / 4 )) GB per sort while Nextflow only books
    // ${MED_MEM_GB} GB for it; two concurrent sorts then exceed the whole machine and
    // the kernel OOM-kills them (observed: samtools at 4.4 GB RSS, exit 137,
    // and on WSL the VS Code server drops with it). Tie the per-thread buffer
    // to the booked memory (70 % of it, split across threads) so real usage
    // matches the request, and give sorts fewer threads - each thread is a
    // separate buffer and the sort is I/O bound on a small genome anyway.
    withName: '.*SAMTOOLS_SORT' {
        cpus     = { ${LOW_CPUS} * task.attempt }
        ext.args = { "-m \${(task.memory.mega * 0.7 / task.cpus).intValue()}M" }
    }
    // The UMI name-sort must keep the '-n' that the pipeline's modules.config
    // gives it; the selector above would otherwise replace it.
    withName: 'NFCORE_RIBOSEQ:RIBOSEQ:BAM_DEDUP_UMI:SAMTOOLS_SORT' {
        ext.args = { "-n -m \${(task.memory.mega * 0.7 / task.cpus).intValue()}M" }
    }
}
EOF
log "wrote nextflow.config (high=${HIGH_CPUS}c/${HIGH_MEM_GB}G, ceiling=${THREADS}c/${MAX_MEM_GB}G)"

# -----------------------------------------------------------------------------
# 2. Pre-flight checks - fail here, not two hours in
# -----------------------------------------------------------------------------
log "pre-flight checks ..."
python3 - "$SAMPLESHEET" <<'PY'
import csv, sys, os
rows = list(csv.DictReader(open(sys.argv[1], newline='')))
missing = [r['fastq_1'] for r in rows if not os.path.exists(r.get('fastq_1',''))]
if missing:
    print("[error] FASTQ files missing:", *missing[:5], sep="\n    ")
    sys.exit(1)
types = {r.get('type') for r in rows}
if not {'riboseq','rnaseq'} & types:
    print(f"[error] samplesheet 'type' column must contain riboseq/rnaseq, got {types}")
    sys.exit(1)
print(f"[pipeline] {len(rows)} samples, types={sorted(types)} - OK")
PY

# -----------------------------------------------------------------------------
# 3. Run
# -----------------------------------------------------------------------------
NEXTFLOW_BIN="${CONDA_PREFIX}/bin/nextflow"
[[ -x "$NEXTFLOW_BIN" ]] || NEXTFLOW_BIN="$(command -v nextflow)"
log "nextflow: ${NEXTFLOW_BIN} ($("$NEXTFLOW_BIN" -v 2>&1))"

CONTRASTS_ARG=()
if [[ -f "${PROJECT_DIR}/contrasts.csv" ]]; then
    # anota2seq needs >=3 samples per condition when there are only two
    # conditions. Below that it aborts the whole run, so only pass --contrasts
    # when it can actually work.
    NMIN=$(python3 - "$PROJECT_DIR/samplesheet.csv" <<'PY'
import csv,sys,collections
rows=list(csv.DictReader(open(sys.argv[1],newline='')))
c=collections.Counter((r.get('type'),r.get('condition')) for r in rows)
print(min(c.values()) if c else 0)
PY
)
    if (( NMIN >= 3 )); then
        CONTRASTS_ARG=(--contrasts "${PROJECT_DIR}/contrasts.csv")
        log "n=${NMIN} per group - anota2seq enabled"
    else
        log "n=${NMIN} per group - SKIPPING --contrasts (anota2seq needs >=3);"
        log "  translational efficiency is computed instead by scripts 05-07"
    fi
fi

log "launching ${PIPELINE} ${PIPELINE_REV} ..."
"$NEXTFLOW_BIN" run "$PIPELINE" \
    -r "$PIPELINE_REV" \
    -c "${PROJECT_DIR}/nextflow.config" \
    -profile singularity \
    -work-dir "$WORK_DIR" \
    -resume \
    --input "$SAMPLESHEET" \
    --outdir "$RESULTS_DIR" \
    --gtf "${PROJECT_DIR}/genome.exons.gtf" \
    --fasta "${PROJECT_DIR}/genome.fasta" \
    "${CONTRASTS_ARG[@]}" \
    2>&1 | tee "${LOG_DIR}/nextflow_$(date +%Y%m%d_%H%M%S).log"

log "done. Next:  bash scripts/run_all.sh --from te"
